#!/usr/bin/env python3
"""Synchronize third-party notices from the JARs installed in lib.

Offline, Python 3.11+, standard library only. licenses.json is generated output.
Embedded notices and Maven license declarations are read before using fallbacks.
"""

import argparse
from fnmatch import fnmatchcase
import hashlib
import io
import json
from pathlib import Path
import re
from tempfile import TemporaryDirectory
from urllib.parse import urlsplit
import xml.etree.ElementTree as ET
import zipfile

ROOT = Path(__file__).resolve().parents[2]
GENERATED = "Generated by extra/licenses/sync_licenses.py. Do not edit this file.\n\n"
PROTECTED = {"jhelioviewer.txt", "eula.txt", "kakadu.txt", "ffmpeg-notices.txt"}
EXTERNAL_LICENSES = {"FFmpeg-Notices.txt": ["GPL-3.0.txt"]}
NOTICE_NAME = re.compile(
    r"(^|[/_.-])(license|licence|notice|copying|copyright)([_.-]|$)", re.I
)
SHARED = (
    "Apache-2.0.txt",
    "MIT.txt",
    "LGPL-2.1.txt",
    "LGPL-3.0.txt",
    "GPL-3.0.txt",
    "GPL-2.0-with-Classpath-Exception.txt",
    "CC-BY-2.5.txt",
)

# Only artifacts missing usable embedded notices/declarations need these.
# These are fallback sources, not evidence about the terms of newer builds.
MISSING_NOTICES = {
    "joml-*.jar": "JOML.txt",
    "jsofa-*.jar": "JSOFA.txt",
    "formats/json-*.jar": "JSON.txt",
    "formats/stil/jcdf.jar": "JCDF.txt",
    "formats/stil/auth.jar": "STIL.txt",
    "formats/stil/fits.jar": "STIL.txt",
    "formats/stil/hapi.jar": "STIL.txt",
    "formats/stil/table.jar": "STIL.txt",
    "formats/stil/util.jar": "STIL.txt",
    "formats/stil/votable.jar": "STIL.txt",
    "ui/jide-oss-*.jar": "JIDE.txt",
    "log/slf4j-*.jar": "SLF4J.txt",
    "lwjgl/lwjgl-*.jar": "LWJGL.txt",
    "jnispice.jar": "SPICE.txt",
    "square/okhttp-jvm-*.jar": "OkHttp.txt",
    "square/logging-interceptor-*.jar": "OkHttp.txt",
    "square/okio-jvm-*.jar": "Okio.txt",
}
# These bundles incorporate code whose notices are missing even when the
# enclosing JAR provides its own license or Maven declaration.
ADDITIONAL_NOTICES = {
    "annotations-*.jar": "Annotations.txt",
    "ehcache-*.jar": "Ehcache.txt",
    "square/kotlin-stdlib-*.jar": "Kotlin.txt",
    "formats/prettytime-nlp-*.jar": "PrettyTime.txt",
}
# Native libraries are detected from actual archive members, not JAR names.
# Keys omit the platform's "lib" prefix and shared-library extension.
NATIVE_NOTICES = {
    "EGL": ("ANGLE.txt",),
    "GLESv2": ("ANGLE.txt",),
    "JNISpice": ("SPICE.txt",),
    "lwjgl": ("LWJGL.txt", "libffi.txt"),
    "lwjgl_opengles": ("LWJGL.txt",),
    "lwjgl_stb": ("LWJGL.txt", "stb.txt"),
    "assimp": ("LWJGL.txt", "Assimp.txt"),
    "draco": ("Draco.txt",),
    "sqlitejdbc": ("SQLite.txt",),
}
EXTERNAL_JARS = {"formats/kdu_jni.jar": "Kakadu.txt"}
EXTERNAL_BINARIES = {
    "ffmpeg": "FFmpeg-Notices.txt",
    "kdu_jni": "Kakadu.txt",
    "kdu_v7AR": "Kakadu.txt",
}


def managed_name(value):
    if not isinstance(value, str) or not re.fullmatch(
        r"[A-Za-z0-9][A-Za-z0-9_.-]*\.txt", value
    ):
        raise ValueError(f"Invalid notice filename: {value!r}")
    if value.casefold() in PROTECTED:
        raise ValueError(f"Protected notice: {value}")
    return value


def clean(text):
    return "\n".join(line.rstrip() for line in text.splitlines()).strip()


def license_pattern(text):
    # Only formatting and the Apache license URL's http/https spelling differ.
    pattern = r"\s+".join(re.escape(word) for word in text.split())
    for scheme in ("http", "https"):
        pattern = pattern.replace(
            re.escape(f"{scheme}://www.apache.org/"), r"https?://www\.apache\.org/"
        )
    return re.compile(pattern)


def declared_terms(url):
    # Resolve this precise standard-license URL, irrespective of library name.
    parsed = urlsplit(url)
    if (
        parsed.scheme in ("http", "https")
        and parsed.netloc == "www.apache.org"
        and parsed.path
        in (
            "/licenses/LICENSE-2.0",
            "/licenses/LICENSE-2.0.txt",
            "/licenses/LICENSE-2.0.html",
        )
        and not parsed.query
        and not parsed.fragment
    ):
        return "Apache-2.0.txt"
    return None


def archive_evidence(archive, location):
    texts, declarations, binaries = [], [], []
    for entry in sorted(archive.namelist()):
        if entry.endswith("/"):
            continue
        source = f"{location}!{entry}"
        if entry.endswith(".jar"):
            with zipfile.ZipFile(io.BytesIO(archive.read(entry))) as nested:
                more_texts, more_declarations, more_binaries = archive_evidence(
                    nested, source
                )
                texts.extend(more_texts)
                declarations.extend(more_declarations)
                binaries.extend(more_binaries)
        elif NOTICE_NAME.search(entry) and not entry.endswith(".class"):
            text = clean(archive.read(entry).decode("utf-8-sig"))
            if text:
                texts.append((source, text))
        elif entry.startswith("META-INF/maven/") and entry.endswith("/pom.xml"):
            pom = ET.fromstring(archive.read(entry))
            for license in pom.findall("./{*}licenses/{*}license"):
                declarations.append(
                    {
                        "source": source,
                        "name": (license.findtext("{*}name") or "").strip(),
                        "url": (license.findtext("{*}url") or "").strip(),
                    }
                )
        elif re.search(r"\.(so(?:\.\d+)*|dylib|dll)$", entry) or Path(entry).name in (
            "ffmpeg",
            "ffmpeg.exe",
        ):
            binaries.append(source)
    return texts, declarations, binaries


def prepare(root):
    """Collect and validate everything before replacing any output."""
    source_dir = root / "extra/licenses"
    output_dir = root / "resources/licenses"
    if not (root / "lib").is_dir():
        raise ValueError("Missing lib directory; refusing to prune license files")
    for directory in (source_dir, output_dir):
        if directory.resolve() != directory:
            raise ValueError(f"License directory must not be a symlink: {directory}")

    shared, spellings = {}, set()
    for name in SHARED:
        managed_name(name)
        if name.casefold() in spellings:
            raise ValueError(f"Duplicate shared license: {name}")
        spellings.add(name.casefold())
        shared[name] = clean((source_dir / name).read_text(encoding="utf-8"))
        if not shared[name]:
            raise ValueError(f"Empty shared license: {name}")
    supplemental_spellings = {}
    for name in (
        *MISSING_NOTICES.values(),
        *ADDITIONAL_NOTICES.values(),
        *(name for names in NATIVE_NOTICES.values() for name in names),
    ):
        managed_name(name)
        if name.casefold() in spellings or name.casefold() == "thirdparty-notices.txt":
            raise ValueError(f"Supplement conflicts with generated output: {name}")
        previous = supplemental_spellings.setdefault(name.casefold(), name)
        if previous != name:
            raise ValueError(f"Conflicting supplement names: {previous}, {name}")

    patterns = {}
    for name, text in shared.items():
        if name == "MIT.txt":
            text = text[text.index("Permission is hereby granted,") :]
        patterns[name] = license_pattern(text)
    used, supplements = set(), set()
    desired = {}
    sections, inventory, errors = [], [], []

    def condense(text):
        for name, pattern in patterns.items():
            text, count = pattern.subn(f"License terms are included in {name}.", text)
            if count:
                used.add(name)
        for name in shared:
            if re.search(r"(?<![\w/.-])" + re.escape(name) + r"\b", text):
                used.add(name)
        return text

    for jar in sorted((root / "lib").rglob("*.jar")):
        relative = jar.relative_to(root / "lib").as_posix()
        location = jar.relative_to(root).as_posix()
        with zipfile.ZipFile(jar) as archive:
            texts, declarations, binaries = archive_evidence(archive, location)
            entries = [n for n in archive.namelist() if not n.endswith("/")]

        additional = {
            name
            for pattern, name in ADDITIONAL_NOTICES.items()
            if fnmatchcase(relative, pattern)
        }
        external = set()
        if relative in EXTERNAL_JARS:
            external.add(EXTERNAL_JARS[relative])
        own_texts = any(source.count("!") == 1 for source, _ in texts)
        own_declarations = [d for d in declarations if d["source"].count("!") == 1]
        resolved = {declared_terms(d["url"]) for d in own_declarations}
        declared = bool(own_declarations) and None not in resolved
        if not own_texts and not declared and not additional and not external:
            additional.update(
                name
                for pattern, name in MISSING_NOTICES.items()
                if fnmatchcase(relative, pattern)
            )

        for source in binaries:
            name = Path(source.rsplit("!", 1)[1]).name.split(".")[0].removeprefix("lib")
            if name in EXTERNAL_BINARIES:
                external.add(EXTERNAL_BINARIES[name])
            elif name in NATIVE_NOTICES:
                additional.update(NATIVE_NOTICES[name])
            elif not own_texts:
                errors.append(f"No native notice found for {source}")
        # These archives mix independently licensed binaries and have no umbrella
        # license. Do not silently ignore a newly added resource.
        if relative.startswith("jhv/jhv-natives-"):
            known = {source.removeprefix(location + "!") for source in binaries}
            unknown = set(entries) - known - {"META-INF/MANIFEST.MF"}
            errors.extend(
                f"Unrecognized native archive member: {location}!{n}"
                for n in sorted(unknown)
            )

        if not (own_texts or declared or additional or external):
            errors.append(
                f"No license text found for {location}. Supply its upstream notice."
            )
        for name in external:
            if name.casefold() not in PROTECTED or not (output_dir / name).is_file():
                errors.append(f"Missing externally maintained notice: {name}")
        supplements.update(additional)

        parts = [location, "-" * len(location)]
        for source, text in texts:
            parts.extend(["", f"Source: {source}", "", condense(text)])
        for declaration in declarations:
            terms = declared_terms(declaration["url"])
            if terms:
                if terms not in shared:
                    raise ValueError(f"Missing shared license: {terms}")
                used.add(terms)
            parts.extend(
                [
                    "",
                    f"Declared in {declaration['source']}:",
                    declaration["name"],
                    declaration["url"],
                ]
            )
            if terms:
                parts.append(f"License terms are included in {terms}.")
        if additional:
            parts.extend(
                ["", "Supplemental notices: " + ", ".join(sorted(additional)) + "."]
            )
        if external:
            parts.extend(
                [
                    "",
                    "Separately maintained notices: "
                    + ", ".join(sorted(external))
                    + ".",
                ]
            )
        sections.append("\n".join(parts))

        with jar.open("rb") as stream:
            checksum = hashlib.file_digest(stream, "sha256").hexdigest()
        inventory.append(
            {
                "path": location,
                "sha256": checksum,
                "embedded_notices": [source for source, _ in texts],
                "declarations": declarations,
                "supplemental_notices": [
                    "extra/licenses/" + name for name in sorted(additional)
                ],
                "external_notices": [
                    "resources/licenses/" + name for name in sorted(external)
                ],
                "native_members": binaries,
            }
        )

    if errors:
        raise ValueError("\n".join(errors))
    for name in sorted(supplements):
        text = clean((source_dir / name).read_text(encoding="utf-8"))
        if not text:
            raise ValueError(f"Empty supplement: {name}")
        desired[name] = GENERATED + condense(text) + "\n"
    for name, licenses in EXTERNAL_LICENSES.items():
        if (output_dir / name).exists():
            for license_name in licenses:
                if license_name not in shared:
                    raise ValueError(f"{name} requires {license_name}")
                used.add(license_name)
    if sections:
        desired["ThirdParty-Notices.txt"] = GENERATED + "\n\n".join(sections) + "\n"
    desired.update({name: GENERATED + shared[name] + "\n" for name in sorted(used)})
    report = {
        "generated_by": "extra/licenses/sync_licenses.py",
        "description": "Installed artifacts and sources of notices. Supplemental texts are not automatically verified against new builds.",
        "shared_licenses": ["resources/licenses/" + name for name in sorted(used)],
        "artifacts": inventory,
    }
    return desired, json.dumps(report, indent=2, ensure_ascii=False) + "\n"


def changes(root, desired):
    output_dir = root / "resources/licenses"
    updates = {}
    removals = []
    for name in desired:
        managed_name(name)
    for path in sorted(output_dir.glob("*.txt")):
        if path.name.casefold() in PROTECTED:
            continue
        if path.is_symlink():
            raise ValueError(f"Refusing symlink: {path}")
        text = path.read_text(encoding="utf-8")
        if path.name in desired:
            if not text.startswith(GENERATED):
                raise ValueError(f"Refusing to overwrite an unmanaged file: {path}")
        elif text.startswith(GENERATED):
            managed_name(path.name)
            removals.append(path)
    for name, text in desired.items():
        path = output_dir / name
        if not path.exists() or path.read_bytes() != text.encode("utf-8"):
            updates[path] = text
    return updates, removals


def sync(root, check=False):
    root = root.resolve()
    desired, report = prepare(root)
    updates, removals = changes(root, desired)
    report_path = root / "extra/licenses/licenses.json"
    if report_path.is_symlink():
        raise ValueError(f"Refusing symlink: {report_path}")
    if not report_path.exists() or report_path.read_bytes() != report.encode("utf-8"):
        updates[report_path] = report
    if not updates and not removals:
        print("License files are in sync.")
        return
    for path in updates:
        print(f"Write {path.relative_to(root)}")
    for path in removals:
        print(f"Remove {path.relative_to(root)}")
    if check:
        raise ValueError("License files are out of sync. Run extra/licenses/sync_licenses.py.")
    output_dir = root / "resources/licenses"
    output_dir.mkdir(parents=True, exist_ok=True)
    with TemporaryDirectory(prefix=".license-sync-", dir=output_dir) as temporary:
        for path, text in updates.items():
            (Path(temporary) / path.name).write_text(
                text, encoding="utf-8", newline="\n"
            )
        for path in updates:
            (Path(temporary) / path.name).replace(path)
        for path in removals:
            path.unlink()
    print("License files synchronized.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Check without writing or deleting files"
    )
    args = parser.parse_args()
    try:
        sync(ROOT, args.check)
    except (OSError, ValueError, ET.ParseError, zipfile.BadZipFile) as error:
        parser.exit(1, f"{error}\n")


if __name__ == "__main__":
    main()
