[{"instrument":"SECCHI",
  "measurement":"171",
  "color":"STEREO EUVI 171 Å"},
 {"instrument":"SECCHI",
  "measurement":"284",
  "color":"STEREO EUVI 284 Å"},
 {"instrument":"SECCHI",
  "measurement":"195",
  "color":"STEREO EUVI 195 Å"},
 {"instrument":"SECCHI",
  "measurement":"304",
  "color":"STEREO EUVI 304 Å"},
 {"instrument":"SECCHI",
  "detector": "COR1", 
  "color":"Red Temperature"},
 {"instrument":"SECCHI",
  "detector": "COR2", 
  "color":"Red Temperature"},

 {"instrument":"EIT",
  "measurement":"171",
  "color":"SOHO EIT 171 Å"},
 {"instrument":"EIT",
  "measurement":"195",
  "color":"SOHO EIT 195 Å"},
 {"instrument":"EIT",
  "measurement":"284",
  "color":"SOHO EIT 284 Å"},
 {"instrument":"EIT",
  "measurement":"304",
  "color":"SOHO EIT 304 Å"},
 {"instrument":"LASCO",
  "detector":"C2",
  "color":"Red Temperature"},
 {"instrument":"LASCO",
  "detector":"C3",
  "color":"Blue/White Linear"},

 {"instrument":"AIA",
  "measurement":"94",
  "color":"SDO-AIA 94 Å"},
 {"instrument":"AIA",
  "measurement":"131",
  "color":"SDO-AIA 131 Å"},
 {"instrument":"AIA",
  "measurement":"171",
  "color":"SDO-AIA 171 Å"},
 {"instrument":"AIA",
  "measurement":"193",
  "color":"SDO-AIA 193 Å"},
 {"instrument":"AIA",
  "measurement":"211",
  "color":"SDO-AIA 211 Å"},
 {"instrument":"AIA",
  "measurement":"304",
  "color":"SDO-AIA 304 Å"},
 {"instrument":"AIA",
  "measurement":"335",
  "color":"SDO-AIA 335 Å"},
 {"instrument":"AIA",
  "measurement":"1600",
  "color":"SDO-AIA 1600 Å"},
 {"instrument":"AIA",
  "measurement":"1700",
  "color":"SDO-AIA 1700 Å"},
 {"instrument":"AIA",
  "measurement":"4500",
  "color":"SDO-AIA 4500 Å"},

 {"instrument":"SWAP",
  "measurement":"174",
  "color":"SDO-AIA 171 Å"},

 {"instrument":"SXT",
  "color":"Yohkoh SXT"},
 {"instrument":"XRT",
  "color":"Red Temperature"},

 {"instrument":"SUVI",
  "measurement":"94",
  "color":"SDO-AIA 94 Å"},
 {"instrument":"SUVI",
  "measurement":"131",
  "color":"SDO-AIA 131 Å"},
 {"instrument":"SUVI",
  "measurement":"171",
  "color":"SDO-AIA 171 Å"},
 {"instrument":"SUVI",
  "measurement":"195",
  "color":"SDO-AIA 193 Å"},
 {"instrument":"SUVI",
  "measurement":"284",
  "color":"SDO-AIA 335 Å"},
 {"instrument":"SUVI",
  "measurement":"304",
  "color":"SDO-AIA 304 Å"},

 {"instrument":"Euhforia",
  "color":"Citrus"},

 {"instrument":"RHESSI",
  "color":"RHESSI"},

 {"instrument":"EUI",
  "measurement":"174",
  "color":"SDO-AIA 171 Å"},
 {"instrument":"EUI",
  "measurement":"304",
  "color":"SDO-AIA 304 Å"},
 {"instrument":"EUI",
  "measurement":"1216",
  "color":"SOLO EUI HRI-LYA"},

 {"instrument":"Hi-C",
  "color":"SDO-AIA 193 Å"},
 {"instrument":"Hi-C2.1",
  "color":"SDO-AIA 171 Å"},

 {"instrument":"SJI",
  "measurement":"1330",
  "color":"IRIS SJI 1330 Å"},
 {"instrument":"SJI",
  "measurement":"1400",
  "color":"IRIS SJI 1400 Å"},
 {"instrument":"SJI",
  "measurement":"2796",
  "color":"IRIS SJI 2796 Å"},
 {"instrument":"SJI",
  "measurement":"2832",
  "color":"IRIS SJI 2832 Å"},

 {"instrument":"Metis",
  "measurement":"UV Lyman-alpha intensity",
  "color":"Metis UV Lyman-alpha intensity"},
 {"instrument":"Metis",
  "measurement":"VL polarized brightness",
  "color":"Metis VL polarized brightness"},
 {"instrument":"Metis",
  "measurement":"VL total brightness",
  "color":"Metis VL total brightness"},

 {"instrument":"CCOR1",
  "color":"CCOR"},
]

// {"instrument":"SJI",
//  "measurement":"1600",
//  "color":"IRIS SJI 1600 Å"},

// Configuration about the used default color tables
// This must be an array and the fist matching rule will be used
// A rule can query "observatory", "instrument", "detector", "measurement"
// which must be equal to the meta information of the layer. Leaving out
// will match to any layer.
//
// The case will be ignored
//
// The key "color" is the name of the color table to apply
