package org.helioviewer.filter.softwaremode;

import javax.swing.JCheckBox;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.helioviewer.viewmodel.filter.Filter;
import org.helioviewer.viewmodelplugin.filter.FilterPanel;
import org.helioviewer.viewmodelplugin.filter.FilterTabPanelManager.Area;

/**
 * Just a checkbox to check logging
 * 
 * @author Helge Dietert
 */
public class SoftwareModePanel extends FilterPanel {
    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = 2575019207197960303L;
    /**
     * Controlled filter
     */
    private SoftwareModeFilter filter;
    /**
     * Controlled box for logging
     */
    private final JCheckBox loggingBox;

    /**
     * Creates a panel with a checkbox for logging
     */
    public SoftwareModePanel() {
        loggingBox = new JCheckBox("Enable logging");
        loggingBox.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                if (filter != null) {
                    filter.setLogging(loggingBox.isSelected());
                }
            }
        });
        add(loggingBox);
        setEnabled(false);
    }

    /**
     * @see org.helioviewer.viewmodelplugin.filter.FilterPanel#getArea()
     */
    @Override
    public Area getArea() {
        return Area.BOTTOM;
    }

    /**
     * Overridden setEnabled to keep in sync with child elements
     */
    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        loggingBox.setEnabled(enabled);
    }

    /**
     * @see org.helioviewer.viewmodelplugin.filter.FilterPanel#setFilter(org.helioviewer.viewmodel.filter.Filter)
     */
    @Override
    public void setFilter(Filter filter) {
        if (filter != null && filter instanceof SoftwareModeFilter) {
            this.filter = (SoftwareModeFilter) filter;
            setEnabled(true);
        }
    }

}
